### ISSUE TITLE
Unauthorized Error then running Terrafrom plan

### ISSUE THREAD

**Issue by josuablejeru** [gitlabhq/terraform-provider-gitlab#1115]
### GitLab Provider version

3.15.0

### GitLab version

GitLab Enterprise Edition 15.1.0-pre

### Terraform version

v1.2.1

### Relevant Terraform Configuration

```hcl
terraform {
  required_providers {
    gitlab = {
      source  = "gitlabhq/gitlab"
      version = "~>3.15.0"
    }
  }
  backend "http" {
  }
}

variable "gitlab_token" {
  default = "gitlab access token"
  type    = string
}

provider "gitlab" {
  token = var.gitlab_token
}

resource "gitlab_pipeline_schedule" "dependabot" {
  project       = "36600273"
  description   = "dependabot pipeline to update dependencies"
  ref           = "dependabot/bundler/dependabot-omnibus-0.190.0"
  cron          = "49 8 * * *" # 8:49am every day
  active        = true
  cron_timezone = "Berlin"
}

resource "gitlab_pipeline_schedule_variable" "npm_access_token" {
  project              = gitlab_pipeline_schedule.dependabot.project
  pipeline_schedule_id = gitlab_pipeline_schedule.dependabot.id
  key                  = "NPM_ACCESS_TOKEN"
  value                = "EXAMPLE_VARIABLE_VALUE"
}
```

### Relevant log output

```shell
Terraform has been successfully initialized!
╷
│ Error: GET https://gitlab.com/api/v4/user: 401 {message: 401 Unauthorized}
│ 
│   with provider["registry.terraform.io/gitlabhq/gitlab"],
│   on main.tf line 17, in provider "gitlab":
│   17: provider "gitlab" {
│ 
╵
```

### Description

Hello everyone! As you can see from the example and the log, an 401 Unauthorized error is showing up then `terraform plan` or `terraform apply` is run by the Pipeline. As an access token, a Gitlab Group Token was provided which has worked fine in past for all operations. Hope this Bug is not a duplicate, if so please let me know. Thanks

```yml
variables:
  TF_STATE_NAME: default
  TF_CACHE_KEY: default
  TF_gitlab_token: $GITLAB_TOKEN

include:
  - template: Terraform.latest.gitlab-ci.yml # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Terraform/Base.gitlab-ci.yml
  - template: Jobs/SAST-IaC.gitlab-ci.yml # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Jobs/SAST-IaC.gitlab-ci.yml
```
