### ISSUE TITLE
Add GitPod support to the repository via .gitpod.yml

### ISSUE THREAD

**Issue by PatrickRice-KSC** [gitlabhq/terraform-provider-gitlab#919]
### Feature Description

~As new users want to join and contribute, it would be good to have a devcontainer file that could help them set up a local environment more easily. The file can be used either with code spaces or with VSCode and will eventually be usable with GitPod as well. This can also assist with people using the M1 and M2 chip, who may have issues with local testing.~ 
Note on the above - the issue was originally going to add a devcontainer.json file to the repository, but based on the below conversations we've moved to using gitpod instead to align with future GitLab migrations and to allow new contributors to make use of GitPod's free tier to contribute.

As new users want to join and contribute, it would good to have a GitPod description file that will help them set up a GitPod environment more easily. The file should automatically choose the correct version of Go, and optionally spin up the GitLab CE container that is used for integration testing. This can also assist people who has incompatible CPU architectures (such as the M1/M2 chips).

### Do you want to implement this?

- [X] I would like to implement this myself 👷

**Comment by PatrickRice-KSC** [comment]
Hm, it looks like there is [no free tier for GitHub Codespaces](https://docs.github.com/en/billing/managing-billing-for-github-codespaces/about-billing-for-codespaces) the way there is for GitPod - the web edit (which you get from pressing "." in your PR) doesn't support running containers which means it can't be used for running tests.

Given those restrictions, while this would still be useful, it doesn't really facilitate best practices of running tests and things like `make reviewable` prior to submitting a PR.

Despite our conversation in Discord, it seems like gitpod might be a better option here for now. Thoughts @timofurrer ?

**Comment by floh96** [comment]
@PatrickRice-KSC I also think gitpod is the better option.
Also in the longterm because it also supports gitlab.

**Comment by timofurrer** [comment]
@PatrickRice-KSC 

> Despite our conversation in Discord, it seems like gitpod might be a better option here for now.

I agree, let's go ahead with the necessary GitPod setup for now - maybe in the future, we can anyway switch to the devcontainer setup working in GitPod and Codespaces.

**Comment by jtymes** [comment]
I began working on a `.gitpod.yml` for myself last week that might be useful as a starting point. It starts up the `ce` acceptance environment right away. That could be removed, but it seemed like a reasonable default. 

```yml
image: gitpod/workspace-go
tasks:
  - init: |
      docker pull gitlab/gitlab-ce
      docker pull gitlab/gitlab-ee
      go mod tidy  
  - name: Start acceptance environment
    command: make testacc-up
    openMode: split-right
vscode:
    extensions:
        - golang.Go
        - hashicorp.terraform
```
